### ISSUE TITLE
doesn't run under ubuntu 16.04

### ISSUE THREAD

**Issue by aero-108** [dpwe/audfprint#30]
```
./audfprint.py

Traceback (most recent call last):
  File "./audfprint.py", line 24, in <module>
    import audfprint_analyze
  File "/audfprint/audfprint_analyze.py", line 26, in <module>
    import librosa
  File "/usr/local/lib/python2.7/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/__init__.py", line 108, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/__init__.py", line 70, in <module>
    from . import decorators
  File "/usr/local/lib/python2.7/dist-packages/librosa/util/decorators.py", line 67, in <module>
    from numba.decorators import jit as optional_jit
  File "/usr/local/lib/python2.7/dist-packages/numba/__init__.py", line 9, in <module>
    from . import config, errors, runtests, types
  File "/usr/local/lib/python2.7/dist-packages/numba/config.py", line 11, in <module>
    import llvmlite.binding as ll
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/binding/__init__.py", line 10, in <module>
    from .module import *
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/binding/module.py", line 8, in <module>
    from .value import ValueRef
  File "/usr/local/lib/python2.7/dist-packages/llvmlite/binding/value.py", line 9, in <module>
    class Linkage(enum.IntEnum):
AttributeError: 'module' object has no attribute 'IntEnum'

```

anyone has same issue?

**Comment by traceypooh** [comment]
Yes, seeing something like this in last month (slightly different).
Moving our install/setup on to python3 for me seems to be working as workaround so far
(knocks on wood ;-)

**Comment by dpwe** [comment]
I just removed librosa as a dependency, which I'm hoping will fix this.  I don't have access to a 16.04 machine - can you check?

**Comment by traceypooh** [comment]
so using python3 and ubuntu xenial/16.04 there seems to be no issue (just reconfirmed from scratch setup with):

```
apt-get install -y  ffmpeg  frei0r-plugins  git  python3  python3-scipy  python3-pip  python3-matplotlib  software-properties-common  wget  libfreetype6-dev  libpng-dev  pkg-config
  apt-get install -y libsamplerate-dev;  # this allows us to *not* need mega-nerd/SRC.. (identical now)

  git clone https://github.com/dpwe/audfprint.git /audfprint

  # it uses python3 so ensure pip pkg installs go to python3 not 2 (thanks @mek !)
  python3 -m pip install --retries=6 -r /audfprint/requirements.txt


  # run it once to get this over with: ;-)
  #     Matplotlib is building the font cache using fc-list. This may take a moment.
  set +e
  python3 /audfprint/audfprint.py
  set -e
```

**Comment by traceypooh** [comment]
python2 seems to work too.

```
docker run --rm -it ubuntu:xenial

apt-get update
apt-get install -y git python python-pip
git clone https://github.com/dpwe/audfprint.git /audfprint
python -m pip install -r /audfprint/requirements.txt
python /audfprint/audfprint.py
```
seems to work just fine

**Comment by dpwe** [comment]
Great, thanks for checking!
