### ISSUE TITLE
can't run on wondows?

### ISSUE THREAD

**Issue by creboy** [dpwe/audfprint#67]
F:\dm\audio\audfprint-master>python audfprint.py new --dbase fpdbase.pklz 1.mp3
Wed Sep 18 11:32:54 2019 ingesting #0: 1.mp3 ...
Error reading header info from F:\dm\audio\audfprint-master\1.mp3
Traceback (most recent call last):
  File "F:\dm\audio\audfprint-master\audio_read.py", line 216, in __init__
    self._get_info()
  File "F:\dm\audio\audfprint-master\audio_read.py", line 265, in _get_info
    raise ValueError("stream info not found")
ValueError: stream info not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\dm\audio\audfprint-master\audfprint_analyze.py", line 358, in wavfile
2peaks
    d, sr = audio_read.audio_read(filename, sr=self.target_sr, channels=1)
  File "F:\dm\audio\audfprint-master\audio_read.py", line 59, in audio_read
    return audio_read_ffmpeg(filename, sr, channels)
  File "F:\dm\audio\audfprint-master\audio_read.py", line 79, in audio_read_ffmp
eg
    sample_rate=sr, channels=channels) as input_file:
  File "F:\dm\audio\audfprint-master\audio_read.py", line 218, in __init__
    raise ValueError("Error reading header info from " + filename)
ValueError: Error reading header info from F:\dm\audio\audfprint-master\1.mp3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "audfprint.py", line 504, in <module>
    main(sys.argv)
  File "audfprint.py", line 487, in main
    strip_prefix=args['--wavdir'])
  File "audfprint.py", line 180, in do_cmd
    dur, nhash = analyzer.ingest(hash_tab, filename)
  File "F:\dm\audio\audfprint-master\audfprint_analyze.py", line 452, in ingest
    hashes = self.wavfile2hashes(filename)
  File "F:\dm\audio\audfprint-master\audfprint_analyze.py", line 400, in wavfile
2hashes
    peaks = self.wavfile2peaks(filename, self.shifts)
  File "F:\dm\audio\audfprint-master\audfprint_analyze.py", line 363, in wavfile
2peaks
    raise IOError(message)
OSError: wavfile2peaks: Error reading 1.mp3

F:\dm\audio\audfprint-master>

**Comment by creboy** [comment]
1.mp3 in the same folder

**Comment by dpwe** [comment]
It's having a problem running ffmpeg on the mp3 file, or in parsing the
results.

Can you run "ffmpeg -i 1.mp3" and paste the output here?

I'm running with ffmpeg version 2.5.4 and it's fine.

It's possible that there's a problem with 1.mp3, which should be evident
from the ffmpeg info output.

  DAn.

**Comment by xuboot** [comment]
ffmpeg 2.5.4 has no windwos version, are you running in a linux system, I also encountered this problem

**Comment by xuboot** [comment]
> ffmpeg 2.5.4没有windwos版本，你是在linux系统下运行的，我也遇到这个问题
