### ISSUE TITLE
what should be the format of mp3 files ? audfprint.py not working

### ISSUE THREAD

**Issue by ksharm50** [dpwe/audfprint#74]
PS Z:\experimental_codebase\audio_fingerprint> python audfprint.py new --dbase fpdbase.pklz Z:\experimental_codebase\audio_fingerprint\Fingerprint_files\*.mp3
Fri Jan 17 12:51:15 2020 ingesting #0: Z:\experimental_codebase\audio_fingerprint\Fingerprint_files\*.mp3 ...
Z:\experimental_codebase\audio_fingerprint\Fingerprint_files\*.mp3 not found.
Traceback (most recent call last):
  File "Z:\experimental_codebase\audio_fingerprint\audfprint_analyze.py", line 358, in wavfile2peaks
    d, sr = audio_read.audio_read(filename, sr=self.target_sr, channels=1)
  File "Z:\experimental_codebase\audio_fingerprint\audio_read.py", line 59, in audio_read
    return audio_read_ffmpeg(filename, sr, channels)
  File "Z:\experimental_codebase\audio_fingerprint\audio_read.py", line 79, in audio_read_ffmpeg
    sample_rate=sr, channels=channels) as input_file:
  File "Z:\experimental_codebase\audio_fingerprint\audio_read.py", line 195, in __init__
    raise ValueError(filename + " not found.")
ValueError: Z:\experimental_codebase\audio_fingerprint\Fingerprint_files\*.mp3 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "audfprint.py", line 504, in <module>
    main(sys.argv)
  File "audfprint.py", line 487, in main
    strip_prefix=args['--wavdir'])
  File "audfprint.py", line 180, in do_cmd
    dur, nhash = analyzer.ingest(hash_tab, filename)
  File "Z:\experimental_codebase\audio_fingerprint\audfprint_analyze.py", line 452, in ingest
    hashes = self.wavfile2hashes(filename)
  File "Z:\experimental_codebase\audio_fingerprint\audfprint_analyze.py", line 400, in wavfile2hashes
    peaks = self.wavfile2peaks(filename, self.shifts)
  File "Z:\experimental_codebase\audio_fingerprint\audfprint_analyze.py", line 363, in wavfile2peaks
    raise IOError(message)
OSError: wavfile2peaks: Error reading Z:\experimental_codebase\audio_fingerprint\Fingerprint_files\*.mp3
PS Z:\experimental_codebase\audio_fingerprint>

**Comment by dpwe** [comment]
Apparently your Windows shell doesn't expand glob patterns.  In a
conventional Unix shell, the filename containing a "*" would be replaced by
a list of matching filenames before the program was even launched.
However, the error message shows that audfprint was trying to open a file
with a "*" in the name.

You should look for a more unix-like command-line shell.

  DAn.
